"""QrMaint API client package.

Provides a singleton, rate-limited, fully-typed Python client for the
QrMaint REST API (https://api.qrmaint.com/v1).

Quick start::

    from qrmaint_api import QrMaintClient

    client = QrMaintClient(api_token="<your-token>")
    assets = client.assets.list()

The client respects all four official rate-limit windows (10/s, 9 000/15 min,
45 000/12 h, 1 000 000/7 days) and returns Pydantic v2 model instances instead
of raw JSON dictionaries.
"""
from __future__ import annotations

from .client import QrMaintClient
from .exceptions import APIError, AuthenticationError, NotFoundError, QrMaintError, RateLimitError, StockSyncValidationError
from .models import (
    AndonCall,
    Asset,
    AssetParams,
    AssetPlannedProductionTime,
    Attachment,
    AttachmentDownloadUrl,
    CreatedObject,
    DictionariesItem,
    DictionariesItemParams,
    DictionaryItem,
    DictionaryItemType,
    DictionaryRootParent,
    Downtime,
    DowntimeParams,
    FailureCode,
    IdType,
    InventoryDocument,
    InventoryDocumentItem,
    InventoryDocumentParams,
    InventoryStockAdjustingParams,
    InventoryStockLog,
    Location,
    LocationParams,
    NewInventoryDocumentItemParams,
    PaginatedResponse,
    Part,
    PartParams,
    PartSupplier,
    PartSupplierParams,
    PartSupplierUpdateParams,
    PartUpdateParams,
    PriorityType,
    ProductionArea,
    ProductionAreaParams,
    ProductionLine,
    ProductionLineParams,
    PurchaseRequest,
    PurchaseRequestItem,
    Shift,
    Stock,
    StockAdjustingParams,
    StockItem,
    StockLog,
    SyncStockQuantitiesParams,
    SyncStockQuantityInvalidItem,
    SyncStockQuantityItem,
    StoragePlace,
    StoragePlaceParams,
    Tag,
    TagType,
    Team,
    UpdatedAssetParams,
    UpdatedDictionaryItemParams,
    UpdatedLocationParams,
    UpdatedObject,
    UpdatedProductionAreaParams,
    UpdatedProductionLineParams,
    UpdatedPurchaseRequestParams,
    UpdatedStockParams,
    UpdatedStoragePlaceParams,
    UpdatedVendorParams,
    UpdatedWorkOrderParams,
    User,
    Vendor,
    VendorParams,
    WorkGroup,
    WorkOrder,
    WorkOrderAssetsOrLocationsAssignmentParams,
    WorkOrderParams,
    WorkOrderShiftsAssignmentParams,
    WorkOrderTeamsAssignmentParams,
    WorkOrderUsersAssignmentParams,
    WorkRequest,
    WorkRequestParams,
)

__all__ = [
    "AndonCall",
    "APIError",
    "Asset",
    "AssetParams",
    "AssetPlannedProductionTime",
    "Attachment",
    "AttachmentDownloadUrl",
    "AuthenticationError",
    "CreatedObject",
    "DictionariesItem",
    "DictionariesItemParams",
    "DictionaryItem",
    "DictionaryItemType",
    "DictionaryRootParent",
    "Downtime",
    "DowntimeParams",
    "FailureCode",
    "IdType",
    "InventoryDocument",
    "InventoryDocumentItem",
    "InventoryDocumentParams",
    "InventoryStockAdjustingParams",
    "InventoryStockLog",
    "Location",
    "LocationParams",
    "NewInventoryDocumentItemParams",
    "NotFoundError",
    "PaginatedResponse",
    "Part",
    "PartParams",
    "PartSupplier",
    "PartSupplierParams",
    "PartSupplierUpdateParams",
    "PartUpdateParams",
    "PriorityType",
    "ProductionArea",
    "ProductionAreaParams",
    "ProductionLine",
    "ProductionLineParams",
    "PurchaseRequest",
    "PurchaseRequestItem",
    "QrMaintClient",
    "QrMaintError",
    "RateLimitError",
    "Shift",
    "StockSyncValidationError",
    "Stock",
    "StockAdjustingParams",
    "StockItem",
    "StockLog",
    "SyncStockQuantitiesParams",
    "SyncStockQuantityInvalidItem",
    "SyncStockQuantityItem",
    "StoragePlace",
    "StoragePlaceParams",
    "Tag",
    "TagType",
    "Team",
    "UpdatedAssetParams",
    "UpdatedDictionaryItemParams",
    "UpdatedLocationParams",
    "UpdatedObject",
    "UpdatedProductionAreaParams",
    "UpdatedProductionLineParams",
    "UpdatedPurchaseRequestParams",
    "UpdatedStockParams",
    "UpdatedStoragePlaceParams",
    "UpdatedVendorParams",
    "UpdatedWorkOrderParams",
    "User",
    "Vendor",
    "VendorParams",
    "WorkGroup",
    "WorkOrder",
    "WorkOrderAssetsOrLocationsAssignmentParams",
    "WorkOrderParams",
    "WorkOrderShiftsAssignmentParams",
    "WorkOrderTeamsAssignmentParams",
    "WorkOrderUsersAssignmentParams",
    "WorkRequest",
    "WorkRequestParams",
]
